spring:
  application:
    name: spring-boot-demo
  profiles:
    active: dev
  cloud:
    nacos:
     config:
       server-addr: 172.24.20.32:8848
       file-extension: yml
#       加载nacos配置中心配置文件
  config:
    import: ${spring.application.name}.${spring.cloud.nacos.config.file-extension}

